export const GET_POKEDEX = {
    SUCCESS: "GET_POKEDEX_SUCCESS",
    PENDING: "GET_POKEDEX_PENDING",
    FAILURE: "GET_POKEDEX_FAILURE"
}

export const PUT_POKEDEX = {
    SUCCESS: "PUT_POKEDEX_SUCCESS",
    PENDING: "PUT_POKEDEX_PENDING",
    FAILURE: "PUT_POKEDEX_FAILURE"
}